-- SparkPoint Localization - English (US)

local _, addon = ...
local L = addon.L

--------------------------------------------------------------------------------
-- General
--------------------------------------------------------------------------------
L["Attach to Cursor"] = "Attach to Cursor"
L["Attach to Cursor Tooltip"] = "When enabled, the ring follows your cursor. When disabled, it stays at a fixed position."
L["Horizontal Offset"] = "Horizontal Offset"
L["Horizontal Offset Tooltip"] = "Horizontal offset from cursor position"
L["Vertical Offset"] = "Vertical Offset"
L["Vertical Offset Tooltip"] = "Vertical offset from cursor position"
L["Anchor Horizontal Offset"] = "Anchor Horizontal Offset"
L["Anchor Vertical Offset"] = "Anchor Vertical Offset"
L["Modules"] = "Modules"
L["Spark Point"] = "Spark Point"
L["Show Minimap Button"] = "Show Minimap Button"
L["Show Minimap Button Tooltip"] = "Show a Spark Point minimap button that opens settings."
L["Minimap Button Click Tooltip"] = "Click to open settings"
L["Fade Minimap Button"] = "Fade Minimap Button"
L["Fade Minimap Button Tooltip"] = "Fade the Spark Point minimap button when your cursor is not over the minimap."
L["Minimap Button Fade Opacity"] = "Minimap Button Fade Opacity"
L["Minimap Button Fade Opacity Tooltip"] = "Opacity used when the minimap button is faded."

--------------------------------------------------------------------------------
-- Common Settings
--------------------------------------------------------------------------------
L["Radius"] = "Radius"
L["Radius Tooltip"] = "Size of the ring"
L["Thickness"] = "Thickness"
L["Thickness Tooltip"] = "Thickness of the ring"
L["Size"] = "Size"
L["Font Size"] = "Font Size"
L["Rotate"] = "Rotate"
L["Rotate Tooltip"] = "Enable rotation animation"
L["Cast Radius"] = "Cast Radius"
L["Cast Thickness"] = "Cast Thickness"

L["Cast Reverse Channeling"] = "Cast Reverse Channeling"
L["Cast Show Spell Name"] = "Cast Show Spell Name"
L["Cast Spell Text Size"] = "Cast Spell Text Size"
L["Cast Spell Text Font"] = "Cast Spell Text Font"
L["Cast Spell Text Outline"] = "Cast Spell Text Outline"
L["Cast Spell Text Offset X"] = "Cast Spell Text Offset X"
L["Cast Spell Text Offset Y"] = "Cast Spell Text Offset Y"
L["Cast Bar Color"] = "Cast Bar Color"
L["Cast Background Opacity"] = "Cast Background Opacity"
L["Cast Background Opacity Tooltip"] = "Opacity of the cast ring background"
L["Cast Frame Opacity"] = "Cast Frame Opacity"
L["Cast Frame Opacity Tooltip"] = "Opacity of the cast ring frame"
L["Cast Glow Opacity"] = "Cast Glow Opacity"
L["Cast Glow Opacity Tooltip"] = "Opacity of the cast glow overlay"
L["Click Feedback"] = "Click Feedback"
L["Click Feedback Enabled"] = "Enable Click Feedback"
L["Click Feedback Enabled Tooltip"] = "Show a ring highlight while mouse buttons are held"
L["Click Feedback Left"] = "Left Click"
L["Click Feedback Left Tooltip"] = "Trigger click feedback while holding left mouse button"
L["Click Feedback Right"] = "Right Click"
L["Click Feedback Right Tooltip"] = "Trigger click feedback while holding right mouse button (camera turn)"
L["Click Feedback Opacity"] = "Click Feedback Class Color Opacity"
L["Click Feedback Opacity Tooltip"] = "Opacity used for the click feedback ring when class color is enabled"
L["Click Feedback Use Class Color"] = "Click Feedback Use Class Color"
L["Click Feedback Use Class Color Tooltip"] = "Use your class color for the click feedback ring"
L["Click Feedback Left Color"] = "Left Click Color"
L["Click Feedback Left Color Tooltip"] = "Color for left-click feedback when class color is disabled"
L["Click Feedback Right Color"] = "Right Click Color"
L["Click Feedback Right Color Tooltip"] = "Color for right-click feedback when class color is disabled"
L["Cast Spark Color"] = "Cast Spark Color"
L["Cast Latency Color"] = "Cast Latency Color"
L["Cast Spell Text Color"] = "Cast Spell Text Color"
L["Cast Use Class Color"] = "Cast Use Class Color"
L["Cast Use Class Color Tooltip"] = "Override cast colors with your class color"
L["Inner Ring Slots"] = "Inner Ring Slots"
L["Slot"] = "Slot"
L["Slot Source"] = "Slot"
L["Source"] = "Source"
L["Slot Source Tooltip"] = "Choose what to display in inner ring slot"
L["None"] = "None"
L["Background Opacity"] = "Background Opacity"
L["Slot Background Opacity Tooltip"] = "Opacity of the slot background ring"
L["Use Class Color"] = "Use Class Color"
L["Slot Use Class Color Tooltip"] = "Override slot bar color with your class color"
L["Visibility"] = "Visibility"
L["Profiles"] = "Profiles"
L["Profile Mode"] = "Profile Mode"
L["Profile Mode Tooltip"] = "Choose whether SparkPoint uses one account-wide shared profile or one shared profile per class. Changing this reloads the UI."
L["Profile Mode Global"] = "Global"
L["Profile Mode Class"] = "Class Specific"
L["Profile Mode Change Confirm"] = "Switch profile mode to %s? This will reload the interface."
L["Copy Settings From"] = "Copy Settings From"
L["Copy Settings From Tooltip"] = "Copy settings from another existing profile into the current profile"
L["Copy Profile Select"] = "Select Profile..."
L["Profile Copy Confirm"] = "Copy settings from %s to %s? This will overwrite the current profile settings."
L["Visibility Source"] = "Visibility Source"
L["Visibility Source Tooltip"] = "Choose whether this module inherits the global visibility setting or uses its own visibility"
L["Visibility Inherit"] = "Inherit"
L["Visibility Custom"] = "Custom"
L["Addon Visibility"] = "Addon Visibility"
L["Addon Visibility Tooltip"] = "Default visibility rule used by modules set to inherit"
L["Hide While Hovering UI"] = "Hide While Hovering UI"
L["Hide While Hovering UI Tooltip"] = "Hide Spark Point while cursor is over clickable UI frames. Keeps Spark Point visible primarily for world targeting."
L["Class Resource Horizontal Offset"] = "Class Resource Horizontal Offset"
L["Class Resource Vertical Offset"] = "Class Resource Vertical Offset"
L["Class Resource Scale"] = "Class Resource Scale"
L["Class Resource Scale Tooltip"] = "Scale for the class resource display"
L["Class Resource Opacity"] = "Class Resource Opacity"
L["Class Resource Opacity Tooltip"] = "Opacity for the class resource display"
L["Class Resource Fill Color"] = "Class Resource Fill Color"
L["Class Resource Fill Color Tooltip"] = "Color for active class resource pips"
L["Class Resource Use Class Color"] = "Class Resource Use Class Color"
L["Class Resource Use Class Color Tooltip"] = "Override class resource pip fill color with your class color"
L["Class Resource Font Size"] = "Class Resource Font Size"
L["Class Resource Font"] = "Class Resource Font"
L["Class Resource Font Outline"] = "Class Resource Font Outline"
L["Class Resource Font Color"] = "Class Resource Font Color"
L["Class Resource Use Class Color"] = "Class Resource Use Class Color"
L["Class Resource Use Class Color Tooltip"] = "Override class resource text color with your class color"
L["Class Resource Text Horizontal Offset"] = "Class Resource Text Horizontal Offset"
L["Class Resource Text Vertical Offset"] = "Class Resource Text Vertical Offset"
L["Class Resource Mode"] = "Class Resource Mode"
L["Class Resource Mode Text"] = "Text"
L["Class Resource Mode Pips"] = "Pips"
L["Class Resource Mode Tooltip"] = "Switch between text and pips class resource display"
L["Class Resource Text Mode"] = "Text Mode"
L["Class Resource Pips Mode"] = "Pips Mode"
L["Class Resource Visibility"] = "Class Resource Visibility"
L["Class Resource Visibility Tooltip"] = "When to show class resources"
L["Cast Ring Visibility"] = "Cast Ring Visibility"
L["Cast Ring Visibility Tooltip"] = "When to show the cast ring shell"
L["Visibility Always"] = "Always"
L["Visibility In Combat"] = "In Combat"
L["Visibility Out of Combat"] = "Out of Combat"
L["Visibility Has Target"] = "Has Target"
L["Visibility While Casting"] = "While Casting"
L["Visibility After Instant Cast"] = "After Instant Cast"
L["Visibility In Party"] = "In Party"
L["Visibility In Raid"] = "In Raid"
L["Visibility In Instanced Content"] = "In Instanced Content"
L["Visibility Multi Select Tooltip"] = "Select one or more rules. The element shows when any selected rule is true."
L["Decorative Ring Size"] = "Decorative Ring Size"
L["Decorative Ring Rotate"] = "Decorative Ring Rotate"
L["Decorative Ring Texture"] = "Decorative Ring Texture"
L["Decorative Ring Color"] = "Decorative Ring Color"
L["Decorative Ring Visibility"] = "Decorative Ring Visibility"
L["Decorative Ring Visibility Tooltip"] = "When to show the decorative ring"
L["Decorative Ring Use Class Color"] = "Decorative Ring Use Class Color"
L["Decorative Ring Use Class Color Tooltip"] = "Override ring color with your class color"
L["Decorative Ring Class Color Opacity"] = "Decorative Ring Class Color Opacity"
L["Decorative Ring Class Color Opacity Tooltip"] = "Opacity for class color override"
L["Spell Icon Size"] = "Spell Icon Size"
L["Spell Icon Horizontal Offset"] = "Spell Icon Horizontal Offset"
L["Spell Icon Vertical Offset"] = "Spell Icon Vertical Offset"
L["Cast Progress Swipe"] = "Cast Progress Swipe"
L["Show On Instant Casts"] = "Show On Instant Casts"
L["Show On Instant Casts Tooltip"] = "Render the spell icon briefly for instant-cast abilities"
L["Assisted Highlight Size"] = "Assisted Highlight Size"
L["Assisted Highlight Horizontal Offset"] = "Assisted Highlight Horizontal Offset"
L["Assisted Highlight Vertical Offset"] = "Assisted Highlight Vertical Offset"
L["Assisted Highlight Icon Opacity"] = "Assisted Highlight Icon Opacity"
L["Assisted Highlight Icon Opacity Tooltip"] = "Opacity of the assisted highlight spell icon"
L["Assisted Highlight Glow"] = "Assisted Highlight Glow"
L["Assisted Highlight Glow Tooltip"] = "Show a blue glow around the suggested spell icon"
L["Assisted Highlight Glow Color"] = "Assisted Highlight Glow Color"
L["Assisted Highlight Glow Color Tooltip"] = "Color and alpha for the assisted highlight glow layer"
L["Assisted Highlight Keybind Text"] = "Assisted Highlight Keybind Text"
L["Assisted Highlight Keybind Text Tooltip"] = "Show the keybind for the suggested spell when available"
L["Assisted Highlight Keybind Format"] = "Assisted Highlight Keybind Format"
L["Assisted Highlight Keybind Format Tooltip"] = "Choose compact or full keybind text style"
L["Assisted Highlight Keybind Compact"] = "Compact"
L["Assisted Highlight Keybind Full"] = "Full"
L["Assisted Highlight Keybind Font"] = "Assisted Highlight Keybind Font"
L["Assisted Highlight Keybind Font Outline"] = "Assisted Highlight Keybind Font Outline"
L["Assisted Highlight Keybind Font Size"] = "Assisted Highlight Keybind Font Size"
L["Assisted Highlight Keybind Opacity"] = "Assisted Highlight Keybind Opacity"
L["Assisted Highlight Keybind Opacity Tooltip"] = "Opacity multiplier for assisted highlight keybind text"
L["Assisted Highlight Keybind Horizontal Offset"] = "Assisted Highlight Keybind Horizontal Offset"
L["Assisted Highlight Keybind Vertical Offset"] = "Assisted Highlight Keybind Vertical Offset"
L["Assisted Highlight Keybind Color"] = "Assisted Highlight Keybind Color"
L["Assisted Highlight Keybind Color Tooltip"] = "Color and alpha for assisted highlight keybind text"
L["Assisted Highlight CVar Disabled"] = "Blizzard Assisted Highlight is currently disabled. Enable it in Blizzard settings to show suggestions."
L["Assisted Highlight Visibility"] = "Assisted Highlight Visibility"
L["Assisted Highlight Visibility Tooltip"] = "When to show the assisted highlight icon"

--------------------------------------------------------------------------------
-- Cast Ring
--------------------------------------------------------------------------------
L["Cast Ring"] = "Cast Ring"
L["Cast Ring Description"] = "Shows a progress ring around your cursor during spell casts"
L["Reverse Channeling"] = "Reverse Channeling"
L["Reverse Channeling Tooltip"] = "Reverse the direction for channeled spells"
L["Show Spell Name"] = "Show Spell Name"
L["Show Spell Name Tooltip"] = "Display the spell name above the ring"
L["Spell Text Size"] = "Spell Text Size"

--------------------------------------------------------------------------------
-- Class Resource
--------------------------------------------------------------------------------
L["Class Resource"] = "Class Resource"
L["Class Resource Description"] = "Displays class resources near the cursor"

--------------------------------------------------------------------------------
-- Ring
--------------------------------------------------------------------------------
L["Decorative Ring"] = "Decorative Ring"
L["Decorative Ring Description"] = "Displays a decorative rotating ring around the cursor during casts"

--------------------------------------------------------------------------------
-- Spell Icon
--------------------------------------------------------------------------------
L["Spell Icon"] = "Spell Icon"
L["Spell Icon Description"] = "Displays the icon of the spell being cast near the cursor"

--------------------------------------------------------------------------------
-- Assisted Highlight
--------------------------------------------------------------------------------
L["Assisted Highlight"] = "Assisted Highlight"
L["Assisted Highlight Description"] = "Shows the next suggested spell from Blizzard Assisted Highlight"

--------------------------------------------------------------------------------
-- Colors (for future use)
--------------------------------------------------------------------------------
L["Bar Color"] = "Bar Color"
L["Background Color"] = "Background Color"
L["Spark Color"] = "Spark Color"
L["Latency Color"] = "Latency Color"
L["Font Color"] = "Font Color"

--------------------------------------------------------------------------------
-- Messages
--------------------------------------------------------------------------------
L["Position locked"] = "Position locked."
L["Drag to reposition"] = "Drag to reposition. Right-click to lock."
L["Position reset"] = "Position reset to defaults."
