-- SparkPoint Localization - English (US)

local _, addon = ...
local L = addon.L

--------------------------------------------------------------------------------
-- General
--------------------------------------------------------------------------------
L["Attach to Cursor"] = "Attach to Cursor"
L["Attach to Cursor Tooltip"] = "When enabled, the ring follows your cursor. When disabled, it stays at a fixed position."
L["Horizontal Offset"] = "Horizontal Offset"
L["Horizontal Offset Tooltip"] = "Horizontal offset from cursor position"
L["Vertical Offset"] = "Vertical Offset"
L["Vertical Offset Tooltip"] = "Vertical offset from cursor position"
L["Anchor Horizontal Offset"] = "Anchor Horizontal Offset"
L["Anchor Vertical Offset"] = "Anchor Vertical Offset"
L["Modules"] = "Modules"
L["SparkPoint"] = "SparkPoint"
L["Show Minimap Button"] = "Show Minimap Button"
L["Show Minimap Button Tooltip"] = "Show a SparkPoint minimap button that opens settings."
L["Minimap Button Click Tooltip"] = "Click to open settings"
L["Fade Minimap Button"] = "Fade Minimap Button"
L["Fade Minimap Button Tooltip"] = "Fade the SparkPoint minimap button when your cursor is not over the minimap."
L["Minimap Button Fade Opacity"] = "Minimap Button Fade Opacity"
L["Minimap Button Fade Opacity Tooltip"] = "Opacity used when the minimap button is faded."

--------------------------------------------------------------------------------
-- Common Settings
--------------------------------------------------------------------------------
L["Radius"] = "Radius"
L["Radius Tooltip"] = "Size of the ring"
L["Thickness"] = "Thickness"
L["Thickness Tooltip"] = "Thickness of the ring"
L["Size"] = "Size"
L["Font Size"] = "Font Size"
L["Rotate"] = "Rotate"
L["Rotate Tooltip"] = "Enable rotation animation"
L["Cast Radius"] = "Radius"
L["Cast Thickness"] = "Thickness"

L["Cast Reverse Channeling"] = "Reverse Channeling"
L["Cast Show Spell Name"] = "Show Spell Name"
L["Cast Spell Text Size"] = "Font Size"
L["Cast Spell Text Font"] = "Font"
L["Cast Spell Text Outline"] = "Font Outline"
L["Cast Spell Text Offset X"] = "Horizontal Offset"
L["Cast Spell Text Offset Y"] = "Vertical Offset"
L["Cast Bar Color"] = "Bar Color"
L["Cast Background Opacity"] = "Background Opacity"
L["Cast Background Opacity Tooltip"] = "Opacity of the cast ring background"
L["Cast Background Color Tooltip"] = "Tint color for the cast ring background texture."
L["Cast Frame Opacity"] = "Frame Opacity"
L["Cast Frame Opacity Tooltip"] = "Opacity of the cast ring frame"
L["Cast Glow Opacity"] = "Glow Opacity"
L["Cast Glow Opacity Tooltip"] = "Opacity of the cast glow overlay"
L["Click Feedback"] = "Click Feedback"
L["Click Feedback Enabled"] = "Enable Click Feedback"
L["Click Feedback Enabled Tooltip"] = "Show a ring highlight while mouse buttons are held"
L["Click Feedback Left"] = "Left Click"
L["Click Feedback Left Tooltip"] = "Trigger click feedback while holding left mouse button"
L["Click Feedback Right"] = "Right Click"
L["Click Feedback Right Tooltip"] = "Trigger click feedback while holding right mouse button (camera turn)"
L["Click Feedback Opacity"] = "Opacity"
L["Click Feedback Opacity Tooltip"] = "Opacity used for the click feedback ring when class color is enabled"
L["Click Feedback Use Class Color"] = "Use Class Color"
L["Click Feedback Use Class Color Tooltip"] = "Use your class color for the click feedback ring"
L["Click Feedback Left Color"] = "Left Click Color"
L["Click Feedback Left Color Tooltip"] = "Color for left-click feedback when class color is disabled"
L["Click Feedback Right Color"] = "Right Click Color"
L["Click Feedback Right Color Tooltip"] = "Color for right-click feedback when class color is disabled"
L["Cast Spark Color"] = "Spark Color"
L["Cast Latency Color"] = "Latency Color"
L["Cast Spell Text Color"] = "Text Color"
L["Cast Spark Use Class Color"] = "Spark Uses Class Color"
L["Cast Spark Use Class Color Tooltip"] = "Use your class color for the cast spark instead of the custom spark color"
L["Cast Spell Text Use Class Color"] = "Spell Text Uses Class Color"
L["Cast Spell Text Use Class Color Tooltip"] = "Use your class color for spell text instead of the custom text color"
L["Inner Ring Slots"] = "Inner Ring Slots"
L["Bar Slots"] = "Bar Slots"
L["Top Bar Slot"] = "Top Bar Slot"
L["Bar Slot Source Tooltip"] = "Choose what to display in the top bar slot"
L["Bar Slot Fill Color Source"] = "Fill Color Source"
L["Bar Slot Fill Color Source Tooltip"] = "Choose how the top bar slot fill color is selected"
L["Bar Slot Fill Color Source Custom"] = "Custom Color"
L["Bar Slot Fill Color Source Class"] = "Class Color"
L["Bar Slot Fill Color Source Provider"] = "Resource Color"
L["Bar Slot Fill Opacity"] = "Fill Opacity"
L["Bar Slot Fill Opacity Tooltip"] = "Opacity of the top bar slot fill regardless of selected color source"
L["Bar Slot Scale"] = "Scale"
L["Bar Slot Scale Tooltip"] = "Scale multiplier for the top bar slot width"
L["Bar Slot Horizontal Offset"] = "Horizontal Offset"
L["Bar Slot Vertical Offset"] = "Vertical Offset"
L["Bar Slot Visibility"] = "Visibility"
L["Bar Slot Visibility Tooltip"] = "When to show the top bar slot module"
L["Bar Slot Background Opacity"] = "Background Opacity"
L["Bar Slot Background Opacity Tooltip"] = "Opacity of the top bar slot background"
L["Bar Frame Color"] = "Frame Color"
L["Bar Frame Color Tooltip"] = "Tint color for the top bar slot frame texture."
L["Bar Slot Frame Opacity"] = "Frame Opacity"
L["Bar Slot Frame Opacity Tooltip"] = "Opacity of the top bar slot frame"
L["Bar Slot Text"] = "Text"
L["Bar Slot Text Tooltip"] = "Show text on the top bar slot"
L["Bar Slot Text Mode"] = "Text Mode"
L["Bar Slot Text Mode Tooltip"] = "Choose how the top bar slot text is formatted"
L["Bar Slot Text Mode Current"] = "Current"
L["Bar Slot Text Mode Current Max"] = "Current / Max"
L["Bar Slot Text Mode Percent"] = "Percent"
L["Bar Slot Text Mode Current Percent"] = "Current + Percent"
L["Bar Slot Text Mode Current Max Percent"] = "Current / Max + Percent"
L["Bar Slot Text Number Style"] = "Number Style"
L["Bar Slot Text Number Style Tooltip"] = "Choose whether current and max values use shortened or full number formatting"
L["Bar Slot Text Number Style Short"] = "Short"
L["Bar Slot Text Number Style Full"] = "Full"
L["Bar Slot Text Font"] = "Font"
L["Bar Slot Text Font Tooltip"] = "Choose the font used by top bar slot text"
L["Bar Slot Text Font Outline"] = "Font Outline"
L["Bar Slot Text Font Outline Tooltip"] = "Choose the outline style used by top bar slot text"
L["Bar Slot Text Font Size"] = "Font Size"
L["Bar Slot Text Color"] = "Text Color"
L["Bar Slot Text Use Class Color"] = "Text Uses Class Color"
L["Bar Slot Text Use Class Color Tooltip"] = "Use your class color for top bar slot text instead of the custom text color"
L["Bar Slot Text Horizontal Offset"] = "Horizontal Offset"
L["Bar Slot Text Vertical Offset"] = "Vertical Offset"
L["Slot"] = "Slot"
L["Slot Source"] = "Slot"
L["Source"] = "Source"
L["Slot Source Tooltip"] = "Choose what to display in inner ring slot"
L["None"] = "None"
L["Background Opacity"] = "Background Opacity"
L["Slot Background Opacity Tooltip"] = "Opacity of the slot background ring"
L["Slot Background Color Tooltip"] = "Tint color for the slot background ring texture."
L["Use Class Color"] = "Use Class Color"
L["Slot Use Class Color Tooltip"] = "Override slot bar color with your class color"
L["Visibility"] = "Visibility"
L["Profiles"] = "Profiles"
L["Profile Mode"] = "Profile Mode"
L["Profile Mode Tooltip"] = "Choose whether SparkPoint uses one account-wide shared profile or one shared profile per class. Changing this reloads the UI."
L["Profile Mode Global"] = "Global"
L["Profile Mode Class"] = "Class Specific"
L["Profile Mode Change Confirm"] = "Switch profile mode to %s? This will reload the interface."
L["Copy Settings From"] = "Copy Settings From"
L["Copy Settings From Tooltip"] = "Copy settings from another existing profile into the current profile"
L["Copy Profile Select"] = "Select Profile..."
L["Profile Copy Confirm"] = "Copy settings from %s to %s? This will overwrite the current profile settings."
L["HUD Frame Strata"] = "HUD Frame Strata"
L["HUD Frame Strata Tooltip"] = "Choose the WoW frame strata used by the entire SparkPoint HUD."
L["HUD Frame Strata Background"] = "Background"
L["HUD Frame Strata Low"] = "Low"
L["HUD Frame Strata Medium"] = "Medium"
L["HUD Frame Strata High"] = "High"
L["HUD Frame Strata Dialog"] = "Dialog"
L["HUD Frame Strata Fullscreen"] = "Fullscreen"
L["HUD Frame Strata FullscreenDialog"] = "Fullscreen Dialog"
L["HUD Frame Strata Tooltip Layer"] = "Tooltip"
L["Visibility Source"] = "Visibility Source"
L["Visibility Source Tooltip"] = "Choose whether this module inherits the global visibility setting or uses its own visibility"
L["Visibility Inherit"] = "Inherit"
L["Visibility Custom"] = "Custom"
L["Hide Overrides"] = "Hide Overrides"
L["Addon Visibility"] = "Addon Visibility"
L["Addon Visibility Tooltip"] = "Default visibility rule used by modules set to inherit"
L["Hide While Hovering UI"] = "Hide While Hovering UI"
L["Hide While Hovering UI Tooltip"] = "Hide SparkPoint while cursor is over clickable UI frames. Keeps SparkPoint visible primarily for world targeting."
L["Transition"] = "Transition"
L["Transition Enabled"] = "Enable Transition"
L["Transition Enabled Tooltip"] = "Enable subtle HUD fade and micro-interaction transitions."
L["Transition In Duration"] = "Fade In Duration"
L["Transition In Duration Tooltip"] = "Duration for HUD fade in."
L["Transition Out Duration"] = "Fade Out Duration"
L["Transition Out Duration Tooltip"] = "Duration for HUD fade out."
L["Transition Easing"] = "Easing"
L["Transition Easing Tooltip"] = "Easing curve used by HUD transitions."
L["Transition Easing OutSine"] = "Out Sine (Smooth)"
L["Transition Easing OutQuad"] = "Out Quad"
L["Transition Easing Linear"] = "Linear"
L["Transition Show Hysteresis"] = "Show Hysteresis"
L["Transition Show Hysteresis Tooltip"] = "Delay before showing after a visibility condition becomes true."
L["Transition Hide Hysteresis"] = "Hide Hysteresis"
L["Transition Hide Hysteresis Tooltip"] = "Delay before hiding after a visibility condition becomes false."
L["Assisted Highlight Glow Transition Enabled"] = "Enable Glow Transition"
L["Assisted Highlight Glow Transition Enabled Tooltip"] = "Enable glow breathing micro-interaction on assisted highlight."
L["Assisted Highlight Glow Transition Speed"] = "Glow Transition Speed"
L["Assisted Highlight Glow Transition Speed Tooltip"] = "Speed multiplier for glow animation cycles."
L["Assisted Highlight Glow Transition Strength"] = "Glow Transition Strength"
L["Assisted Highlight Glow Transition Strength Tooltip"] = "Pulse amplitude: 0 is mostly static, 1 is a full breathing range."
L["Class Resource Horizontal Offset"] = "Horizontal Offset"
L["Class Resource Vertical Offset"] = "Vertical Offset"
L["Class Resource Scale"] = "Scale"
L["Class Resource Scale Tooltip"] = "Scale for the class resource display"
L["Class Resource Opacity"] = "Opacity"
L["Class Resource Opacity Tooltip"] = "Opacity for the class resource display"
L["Class Resource Fill Color"] = "Fill Color"
L["Class Resource Fill Color Tooltip"] = "Color for active class resource pips"
L["Class Resource Background Color Tooltip"] = "Tint multiplier for the class resource pip background texture."
L["Class Resource Use Class Color"] = "Use Class Color"
L["Class Resource Use Class Color Tooltip"] = "Override class resource pip fill color with your class color"
L["Class Resource Font Size"] = "Font Size"
L["Class Resource Font"] = "Font"
L["Class Resource Font Outline"] = "Font Outline"
L["Class Resource Font Color"] = "Font Color"
L["Class Resource Use Class Color"] = "Use Class Color"
L["Class Resource Use Class Color Tooltip"] = "Override class resource text color with your class color"
L["Class Resource Text Horizontal Offset"] = "Horizontal Offset"
L["Class Resource Text Vertical Offset"] = "Vertical Offset"
L["Class Resource Mode"] = "Mode"
L["Class Resource Mode Text"] = "Text"
L["Class Resource Mode Pips"] = "Pips"
L["Class Resource Mode Tooltip"] = "Switch between text and pips class resource display"
L["Class Resource Text Mode"] = "Text Mode"
L["Class Resource Pips Mode"] = "Pips Mode"
L["Class Resource Visibility"] = "Visibility"
L["Class Resource Visibility Tooltip"] = "When to show class resources"
L["Cast Ring Visibility"] = "Visibility"
L["Cast Ring Visibility Tooltip"] = "When to show the cast ring shell"
L["Visibility Always"] = "Always"
L["Visibility Always Tooltip"] = "Keep this element visible at all times. Selecting this clears the other visibility conditions."
L["Visibility In Combat"] = "In Combat"
L["Visibility In Combat Tooltip"] = "Show while you are in combat."
L["Visibility Out of Combat"] = "Out of Combat"
L["Visibility Out of Combat Tooltip"] = "Show while you are out of combat."
L["Visibility Has Target"] = "Has Any Target"
L["Visibility Has Target Tooltip"] = "Show when you have any target selected. The nested target options refine which targets count."
L["Visibility Target Alive"] = "Alive"
L["Visibility Target Alive Tooltip"] = "Only count living targets. Combine with target reaction filters to narrow it further."
L["Visibility Target Dead"] = "Dead"
L["Visibility Target Dead Tooltip"] = "Only count dead or ghost targets. Combine with target reaction filters to narrow it further."
L["Visibility Target Hostile"] = "Hostile / Unfriendly"
L["Visibility Target Hostile Tooltip"] = "Only count hostile or otherwise attackable enemy targets."
L["Visibility Target Neutral"] = "Neutral"
L["Visibility Target Neutral Tooltip"] = "Only count neutral targets that are not friendly but are not currently hostile."
L["Visibility Target Friendly"] = "Friendly"
L["Visibility Target Friendly Tooltip"] = "Only count friendly targets."
L["Visibility While Casting"] = "While Casting"
L["Visibility While Casting Tooltip"] = "Show while you are actively casting or channeling a spell."
L["Visibility After Instant Cast"] = "After Instant Cast"
L["Visibility After Instant Cast Tooltip"] = "Show briefly after an instant spell you directly triggered succeeds."
L["Visibility After Triggered Instant Cast"] = "After Triggered Instant Cast"
L["Visibility After Triggered Instant Cast Tooltip"] = "Show briefly after an instant spell triggered automatically by another action or effect succeeds."
L["Visibility In Party"] = "In Party"
L["Visibility In Party Tooltip"] = "Show while you are in a party group but not a raid."
L["Visibility In Raid"] = "In Raid"
L["Visibility In Raid Tooltip"] = "Show while you are in a raid group."
L["Visibility In Instanced Content"] = "In Instanced Content"
L["Visibility In Instanced Content Tooltip"] = "Show while you are inside an instance such as a dungeon, raid, scenario, or arena."
L["Hide While In Pet Battle"] = "Hide While In Pet Battle"
L["Hide While In Pet Battle Tooltip"] = "Hide SparkPoint while you are in a pet battle."
L["Hide While In Special Action Bar Context"] = "Hide While In Special Action Bar Context"
L["Hide While In Special Action Bar Context Tooltip"] =
	"Hide SparkPoint while Blizzard replaces your normal action bar with a special context such as vehicle, override, possess, or temporary shapeshift bars."
L["Visibility Multi Select Tooltip"] = "Select one or more rules. The element shows when any selected rule is true."
L["Decorative Ring Size"] = "Size"
L["Decorative Ring Rotate"] = "Rotate"
L["Decorative Ring Texture"] = "Texture"
L["Decorative Ring Color"] = "Color"
L["Decorative Ring Visibility"] = "Visibility"
L["Decorative Ring Visibility Tooltip"] = "When to show the decorative ring"
L["Decorative Ring Use Class Color"] = "Use Class Color"
L["Decorative Ring Use Class Color Tooltip"] = "Override ring color with your class color"
L["Decorative Ring Class Color Opacity"] = "Class Color Opacity"
L["Decorative Ring Class Color Opacity Tooltip"] = "Opacity for class color override"
L["Spell Icon Size"] = "Size"
L["Spell Icon Horizontal Offset"] = "Horizontal Offset"
L["Spell Icon Vertical Offset"] = "Vertical Offset"
L["Cast Progress Swipe"] = "Cast Progress Swipe"
L["Cast Progress Swipe Color"] = "Swipe Color"
L["Cast Progress Swipe Color Tooltip"] = "Tint color and opacity of the spell icon cast progress swipe"
L["Readable Cooldown Use Class Color"] = "Use Class Color"
L["Readable Cooldown Use Class Color Tooltip"] = "Override readable cooldown swipe color with your class color while keeping the configured opacity"
L["Readable Cooldown Swipe Color"] = "Readable Cooldown Swipe Color"
L["Readable Cooldown Swipe Color Tooltip"] = "Tint color and opacity of the readable cooldown swipe shown after a blocked press"
L["Show On Instant Casts"] = "Show On Instant Casts"
L["Show On Instant Casts Tooltip"] = "Render the spell icon briefly for instant-cast abilities"
L["Assisted Highlight Size"] = "Size"
L["Assisted Highlight Horizontal Offset"] = "Horizontal Offset"
L["Assisted Highlight Vertical Offset"] = "Vertical Offset"
L["Assisted Highlight Icon Opacity"] = "Icon Opacity"
L["Assisted Highlight Icon Opacity Tooltip"] = "Opacity of the assisted highlight spell icon"
L["Assisted Highlight Glow"] = "Glow"
L["Assisted Highlight Glow Tooltip"] = "Show a blue glow around the suggested spell icon"
L["Assisted Highlight Glow Color"] = "Glow Color"
L["Assisted Highlight Glow Color Tooltip"] = "Color and alpha for the assisted highlight glow layer"
L["Assisted Highlight Keybind Text"] = "Show Keybind Text"
L["Assisted Highlight Keybind Text Tooltip"] = "Show the keybind for the suggested spell when available"
L["Assisted Highlight Keybind Format"] = "Keybind Format"
L["Assisted Highlight Keybind Format Tooltip"] = "Choose compact or full keybind text style"
L["Assisted Highlight Keybind Compact"] = "Compact"
L["Assisted Highlight Keybind Full"] = "Full"
L["Assisted Highlight Keybind Font"] = "Keybind Font"
L["Assisted Highlight Keybind Font Outline"] = "Keybind Font Outline"
L["Assisted Highlight Keybind Font Size"] = "Keybind Font Size"
L["Assisted Highlight Keybind Opacity"] = "Keybind Opacity"
L["Assisted Highlight Keybind Opacity Tooltip"] = "Opacity multiplier for assisted highlight keybind text"
L["Assisted Highlight Keybind Horizontal Offset"] = "Keybind Horizontal Offset"
L["Assisted Highlight Keybind Vertical Offset"] = "Keybind Vertical Offset"
L["Assisted Highlight Keybind Color"] = "Keybind Color"
L["Assisted Highlight Keybind Color Tooltip"] = "Color and alpha for assisted highlight keybind text"
L["Assisted Highlight CVar Disabled"] = "Blizzard Assisted Highlight is currently disabled. Enable it in Blizzard settings to show suggestions."
L["Assisted Highlight Visibility"] = "Visibility"
L["Assisted Highlight Visibility Tooltip"] = "When to show the assisted highlight icon"

--------------------------------------------------------------------------------
-- Cast Ring
--------------------------------------------------------------------------------
L["Cast Ring"] = "Cast Ring"
L["Cast Ring Description"] = "Shows a progress ring around your cursor during spell casts"
L["Reverse Channeling"] = "Reverse Channeling"
L["Reverse Channeling Tooltip"] = "Reverse the direction for channeled spells"
L["Cast Progress Display"] = "Cast Progress Display"
L["Cast Progress Display Tooltip"] = "Choose which cast types animate the progress fill. This does not change overall SparkPoint visibility."
L["Cast Progress Display All"] = "All Casts"
L["Cast Progress Display Normal"] = "Normal Casts Only"
L["Cast Progress Display Channelled"] = "Channelled Spells Only"
L["Cast Fill Color Source"] = "Cast Fill Color Source"
L["Cast Fill Color Source Tooltip"] = "Choose how the main cast ring fill color is selected"
L["Cast Fill Color Source Single"] = "Single Color"
L["Cast Fill Color Source Split"] = "Separate Normal / Channelled Colors"
L["Cast Fill Color Source Class"] = "Class Color"
L["Primary Cast Color"] = "Primary Cast Color"
L["Primary Cast Color Tooltip"] = "Used for all casts in Single Color mode, or normal non-channelled casts in Separate mode"
L["Channelled Cast Color"] = "Channelled Cast Color"
L["Channelled Cast Color Tooltip"] = "Color used for the cast ring fill while channeling"
L["Show Spell Name"] = "Show Spell Name"
L["Show Spell Name Tooltip"] = "Display the spell name above the ring"
L["Spell Text Size"] = "Spell Text Size"

--------------------------------------------------------------------------------
-- Class Resource
--------------------------------------------------------------------------------
L["Class Resource"] = "Class Resource"
L["Class Resource Description"] = "Displays class resources near the cursor"
L["Bar Slots Description"] = "Displays curved top bar slots above the cast ring"

--------------------------------------------------------------------------------
-- Ring
--------------------------------------------------------------------------------
L["Decorative Ring"] = "Decorative Ring"
L["Decorative Ring Description"] = "Displays a decorative rotating ring around the cursor during casts"

--------------------------------------------------------------------------------
-- Spell Icon
--------------------------------------------------------------------------------
L["Spell Icon"] = "Spell Icon"
L["Spell Icon Description"] = "Displays the icon of the spell being cast near the cursor"
L["Show On Instant Casts"] = "Show On Instant Casts"
L["Show On Instant Casts Tooltip"] = "Render the spell icon briefly for instant abilities you directly trigger"
L["Show Triggered Instant Casts"] = "Show Triggered Instant Casts"
L["Show Triggered Instant Casts Tooltip"] = "Also render instant spells triggered automatically after your action, such as procs or follow-up effects"
L["Failed Cast Style"] = "Failed Cast Style"
L["Failed Cast Style Tooltip"] = "Choose how Spell Icon reacts when a cast attempt fails for a reason other than cooldown"
L["Failed Cast Style Hide"] = "Hide"
L["Failed Cast Style Error Icon"] = "Error Icon"
L["Show Cooldown Blocked Presses"] = "Show Readable Cooldown"
L["Show Cooldown Blocked Presses Tooltip"] = "Show the spell icon with remaining cooldown only when Blizzard exposes readable cooldown data for the pressed ability"

--------------------------------------------------------------------------------
-- Assisted Highlight
--------------------------------------------------------------------------------
L["Assisted Highlight"] = "Assisted Highlight"
L["Assisted Highlight Description"] = "Shows the next suggested spell from Blizzard Assisted Highlight"

--------------------------------------------------------------------------------
-- Colors (for future use)
--------------------------------------------------------------------------------
L["Bar Color"] = "Bar Color"
L["Background Color"] = "Background Color"
L["Spark Color"] = "Spark Color"
L["Latency Color"] = "Latency Color"
L["Font Color"] = "Font Color"

--------------------------------------------------------------------------------
-- Messages
--------------------------------------------------------------------------------
L["Position locked"] = "Position locked."
L["Drag to reposition"] = "Drag to reposition. Right-click to lock."
L["Position reset"] = "Position reset to defaults."
