-- SparkPoint Localization - ZamestoTV (RU)

local _, addon = ...
local L = addon.L

--------------------------------------------------------------------------------
-- General
--------------------------------------------------------------------------------
L["Attach to Cursor"] = "Прикрепить к курсору"
L["Attach to Cursor Tooltip"] = "Если включено, кольцо следует за курсором. Если выключено - остается в фиксированной позиции."
L["Horizontal Offset"] = "Смещение по горизонтали"
L["Horizontal Offset Tooltip"] = "Горизонтальное смещение относительно позиции курсора"
L["Vertical Offset"] = "Смещение по вертикали"
L["Vertical Offset Tooltip"] = "Вертикальное смещение относительно позиции курсора"
L["Anchor Horizontal Offset"] = "Смещение якоря по горизонтали"
L["Anchor Vertical Offset"] = "Смещение якоря по вертикали"
L["Modules"] = "Модули"
L["SparkPoint"] = "SparkPoint" 
L["Show Minimap Button"] = "Кнопка у миникарты"
L["Show Minimap Button Tooltip"] = "Показывать кнопку SparkPoint у миникарты для открытия настроек."
L["Minimap Button Click Tooltip"] = "Нажмите, чтобы открыть настройки"
L["Fade Minimap Button"] = "Затемнение кнопки"
L["Fade Minimap Button Tooltip"] = "Кнопка SparkPoint становится прозрачной, когда курсор находится не над миникартой."
L["Minimap Button Fade Opacity"] = "Прозрачность при затухании"
L["Minimap Button Fade Opacity Tooltip"] = "Уровень непрозрачности кнопки миникарты в режиме затухания."

--------------------------------------------------------------------------------
-- Common Settings
--------------------------------------------------------------------------------
L["Radius"] = "Радиус"
L["Radius Tooltip"] = "Размер кольца"
L["Thickness"] = "Толщина"
L["Thickness Tooltip"] = "Толщина линий кольца"
L["Size"] = "Размер"
L["Font Size"] = "Размер шрифта"
L["Rotate"] = "Вращение"
L["Rotate Tooltip"] = "Включить анимацию вращения"
L["Cast Radius"] = "Радиус заклинания"
L["Cast Thickness"] = "Толщина заклинания"

L["Cast Reverse Channeling"] = "Обратное направление потоковых заклинаний"
L["Cast Show Spell Name"] = "Показывать название заклинания"
L["Cast Spell Text Size"] = "Размер шрифта"
L["Cast Spell Text Font"] = "Шрифт"
L["Cast Spell Text Outline"] = "Контур текста"
L["Cast Spell Text Anchor"] = "Привязка текста"
L["Cast Spell Text Offset X"] = "Смещение по горизонтали"
L["Cast Spell Text Offset Y"] = "Смещение по вертикали"
L["Anchor Top"] = "Сверху"
L["Anchor Bottom"] = "Снизу"
L["Anchor Left"] = "Слева"
L["Anchor Right"] = "Справа"
L["Cast Bar Color"] = "Цвет полосы заклинания"
L["Cast Background Opacity"] = "Прозрачность фона"
L["Cast Background Opacity Tooltip"] = "Прозрачность фона кольца применения заклинаний."
L["Cast Background Color Tooltip"] = "Оттенок для текстуры фона кольца заклинаний."
L["Cast Frame Opacity"] = "Прозрачность рамки"
L["Cast Frame Opacity Tooltip"] = "Прозрачность рамки кольца применения заклинаний."
L["Cast Glow Opacity"] = "Прозрачность свечения"
L["Cast Glow Opacity Tooltip"] = "Прозрачность наложения эффекта свечения."
L["Click Feedback"] = "Отклик на нажатия"
L["Click Feedback Enabled"] = "Включить отклик на нажатия"
L["Click Feedback Enabled Tooltip"] = "Показывать подсветку кольца при удержании кнопок мыши."
L["Click Feedback Left"] = "Левая кнопка мыши"
L["Click Feedback Left Tooltip"] = "Активировать отклик при удержании левой кнопки мыши."
L["Click Feedback Right"] = "Правая кнопка мыши"
L["Click Feedback Right Tooltip"] = "Активировать отклик при удержании правой кнопки мыши (поворот камеры)."
L["Click Feedback Opacity"] = "Прозрачность"
L["Click Feedback Opacity Tooltip"] = "Прозрачность кольца отклика при использовании цвета класса."
L["Click Feedback Use Class Color"] = "Цвет класса"
L["Click Feedback Use Class Color Tooltip"] = "Использовать цвет вашего класса для кольца отклика."
L["Click Feedback Left Color"] = "Цвет левой кнопки"
L["Click Feedback Left Color Tooltip"] = "Цвет отклика для левой кнопки мыши (если цвет класса выключен)."
L["Click Feedback Right Color"] = "Цвет правой кнопки"
L["Click Feedback Right Color Tooltip"] = "Цвет отклика для правой кнопки мыши (если цвет класса выключен)."
L["Cast Spark Color"] = "Цвет искры"
L["Cast Latency Color"] = "Цвет задержки"
L["Cast Spell Text Color"] = "Цвет текста заклинания"
L["Cast Spark Use Class Color"] = "Цвет класса для искры"
L["Cast Spark Use Class Color Tooltip"] = "Использовать цвет вашего класса для искры вместо пользовательского цвета."
L["Cast Spell Text Use Class Color"] = "Цвет класса для текста"
L["Cast Spell Text Use Class Color Tooltip"] = "Использовать цвет вашего класса для текста заклинания вместо пользовательского цвета."
L["Inner Ring Slots"] = "Слоты внутреннего кольца"
L["Enable Inner Slots"] = "Включить слоты кольца"
L["Enable Inner Slots Tooltip"] = "Активировать отображение слотов кольца."
L["Inner Slots Visibility Tooltip"] = "Условия отображения слотов кольца."
L["Outer Slot"] = "Внешний слот"
L["Middle Slot"] = "Средний слот"
L["Inner Slot"] = "Внутренний слот"
L["Slot Enabled"] = "Включено"
L["Slot Enabled Tooltip"] = "Активировать этот слот кольца."
L["Bar Slots"] = "Слоты полос"
L["Top Bar Slot"] = "Верхний слот полосы"
L["Top Slot"] = "Верхний слот"
L["Top Slot Enabled"] = "Включить верхний слот"
L["Top Slot Enabled Tooltip"] = "Активировать верхний слот полосы."
L["Bottom Slot"] = "Нижний слот"
L["Bottom Slot Enabled"] = "Включить нижний слот"
L["Bottom Slot Enabled Tooltip"] = "Активировать нижний слот полосы."
L["Class Power or Mana"] = "Ресурс класса или мана"
L["Resource Colors"] = "Цвета ресурсов"
L["Resource Colors Tooltip"] = "Переопределить стандартные цвета ресурсов для всего аддона. Это затронет цвета слотов полос и отображение ресурсов класса."
L["Content"] = "Содержимое"
L["Layout"] = "Расположение"
L["Appearance"] = "Внешний вид"
L["Bar Slot Source Tooltip"] = "Выберите, что отображать в этом слоте полосы"
L["Bar Slot Fill Color Source"] = "Источник цвета заполнения"
L["Bar Slot Fill Color Source Tooltip"] = "Выберите, как определяется цвет заполнения полосы"
L["Bar Slot Fill Color Source Custom"] = "Пользовательский цвет"
L["Bar Slot Fill Color Source Class"] = "Цвет класса"
L["Bar Slot Fill Color Source Provider"] = "Цвет ресурса"
L["Inner Slot Fill Color Source Tooltip"] = "Выберите, как определяется цвет заполнения кольца"
L["Bar Slot Fill Opacity"] = "Прозрачность заполнения"
L["Bar Slot Fill Opacity Tooltip"] = "Прозрачность заполнения полосы независимо от выбранного источника цвета"
L["Inner Slot Fill Opacity Tooltip"] = "Прозрачность заполнения кольца независимо от выбранного источника цвета"
L["Bar Slot Scale"] = "Масштаб"
L["Bar Slot Scale Tooltip"] = "Множитель масштаба для ширины слота полосы"
L["Bar Slot Horizontal Offset"] = "Смещение по горизонтали"
L["Bar Slot Vertical Offset"] = "Смещение по вертикали"
L["Bar Slot Visibility"] = "Видимость"
L["Bar Slot Visibility Tooltip"] = "Условия отображения этого слота полосы"
L["Bar Slot Background Opacity"] = "Прозрачность фона"
L["Bar Slot Background Opacity Tooltip"] = "Прозрачность фона слота полосы"
L["Bar Frame Color"] = "Цвет рамки"
L["Bar Frame Color Tooltip"] = "Цвет (оттенок) для текстуры рамки слота полосы."
L["Bar Slot Frame Opacity"] = "Прозрачность рамки"
L["Bar Slot Frame Opacity Tooltip"] = "Прозрачность рамки слота полосы"
L["Inner Slot Frame Color Tooltip"] = "Оттенок для текстуры рамки слота кольца."
L["Inner Slot Frame Opacity Tooltip"] = "Прозрачность рамки слота кольца"
L["Bar Slot Text"] = "Текст"
L["Bar Slot Text Tooltip"] = "Показывать текст в этом слоте полосы"
L["Bar Slot Text Mode"] = "Режим текста"
L["Bar Slot Text Mode Tooltip"] = "Выберите способ форматирования текста в слоте полосы"
L["Bar Slot Text Mode Current"] = "Текущее"
L["Bar Slot Text Mode Current Max"] = "Текущее / Макс."
L["Bar Slot Text Mode Percent"] = "Проценты"
L["Bar Slot Text Mode Current Percent"] = "Текущее + Проценты"
L["Bar Slot Text Mode Current Max Percent"] = "Текущее / Макс. + Проценты"
L["Bar Slot Text Number Style"] = "Стиль чисел"
L["Bar Slot Text Number Style Tooltip"] = "Выберите формат чисел: сокращенный (напр. 10к) или полный (10000)"
L["Bar Slot Text Number Style Short"] = "Сокращенный"
L["Bar Slot Text Number Style Full"] = "Полный"
L["Bar Slot Text Color Source"] = "Источник цвета текста"
L["Bar Slot Text Color Source Tooltip"] = "Выберите, как определяется цвет текста в слоте полосы"
L["Bar Slot Text Color Source Custom"] = "Пользовательский цвет"
L["Bar Slot Text Color Source Class"] = "Цвет класса"
L["Bar Slot Text Color Source Provider"] = "Цвет ресурса"
L["Bar Slot Text Font"] = "Шрифт"
L["Bar Slot Text Font Tooltip"] = "Выберите шрифт для текста в слоте полосы"
L["Bar Slot Text Font Outline"] = "Контур шрифта"
L["Bar Slot Text Font Outline Tooltip"] = "Выберите стиль окантовки для текста"
L["Bar Slot Text Font Size"] = "Размер шрифта"
L["Bar Slot Text Color"] = "Цвет текста"
L["Bar Slot Text Opacity"] = "Прозрачность текста"
L["Bar Slot Text Opacity Tooltip"] = "Прозрачность текста в слоте независимо от выбранного источника цвета"
L["Bar Slot Text Horizontal Offset"] = "Смещение текста по горизонтали"
L["Bar Slot Text Vertical Offset"] = "Смещение текста по вертикали"
L["Slot"] = "Слот"
L["Slot Source"] = "Источник слота"
L["Source"] = "Источник"
L["Slot Source Tooltip"] = "Выберите, что отображать в этом слоте кольца"
L["None"] = "Нет"
L["Background Opacity"] = "Прозрачность фона"
L["Slot Background Opacity Tooltip"] = "Прозрачность фонового кольца слота"
L["Slot Background Color Tooltip"] = "Оттенок для текстуры фонового кольца слота."
L["Use Class Color"] = "Цвет класса"
L["Slot Use Class Color Tooltip"] = "Переопределить цвет полосы слота цветом вашего класса"
L["Visibility"] = "Видимость"
L["Profiles"] = "Профили"
L["Profile Mode"] = "Режим профилей"
L["Profile Mode Tooltip"] = "Выберите, использовать ли один общий профиль на весь аккаунт или отдельные профили для каждого класса. Смена этого параметра перезагрузит интерфейс."
L["Profile Mode Global"] = "Общий"
L["Profile Mode Class"] = "Для каждого класса"
L["Profile Mode Change Confirm"] = "Переключить режим профилей на %s? Это перезагрузит интерфейс."
L["Copy Settings From"] = "Копировать настройки из..."
L["Copy Settings From Tooltip"] = "Скопировать настройки из другого существующего профиля в текущий"
L["Copy Profile Select"] = "Выберите профиль..."
L["Profile Copy Confirm"] = "Скопировать настройки из %s в %s? Это перезапишет текущие настройки профиля."
L["HUD Frame Strata"] = "Слой интерфейса"
L["HUD Frame Strata Tooltip"] = "Выберите уровень слоя, на котором будет отображаться весь HUD SparkPoint."
L["HUD Frame Strata Background"] = "Фон"
L["HUD Frame Strata Low"] = "Низкий"
L["HUD Frame Strata Medium"] = "Средний"
L["HUD Frame Strata High"] = "Высокий"
L["HUD Frame Strata Dialog"] = "Диалоги"
L["HUD Frame Strata Fullscreen"] = "Полноэкранный"
L["HUD Frame Strata FullscreenDialog"] = "Полноэкранный диалог"
L["HUD Frame Strata Tooltip Layer"] = "Подсказки"
L["Visibility Source"] = "Источник видимости"
L["Visibility Source Tooltip"] = "Выберите, будет ли этот модуль наследовать глобальные настройки видимости или использовать собственные."
L["Visibility Inherit"] = "Наследовать"
L["Visibility Custom"] = "Собственные настройки"
L["Hide Overrides"] = "Скрыть исключения"
L["Addon Visibility"] = "Видимость аддона"
L["Addon Visibility Tooltip"] = "Правило видимости по умолчанию для модулей, у которых установлено Наследовать."
L["Hide While Hovering UI"] = "Скрывать при наведении на интерфейс"
L["Hide While Hovering UI Tooltip"] = "Скрывать SparkPoint, когда курсор находится над кликабельными элементами интерфейса. Это оставляет HUD видимым в основном для взаимодействия с игровым миром."
L["Transition"] = "Переходы"
L["Transition Enabled"] = "Включить переходы"
L["Transition Enabled Tooltip"] = "Включить плавную анимацию появления и затухания HUD."
L["Transition In Duration"] = "Длительность появления"
L["Transition In Duration Tooltip"] = "Время, за которое HUD плавно появляется."
L["Transition Out Duration"] = "Длительность затухания"
L["Transition Out Duration Tooltip"] = "Время, за которое HUD плавно исчезает."
L["Transition Easing"] = "Тип сглаживания"
L["Transition Easing Tooltip"] = "Кривая сглаживания, используемая для анимации переходов HUD."
L["Transition Easing OutSine"] = "Плавно"
L["Transition Easing OutQuad"] = "Ускоренно"
L["Transition Easing Linear"] = "Линейно"
L["Transition Show Hysteresis"] = "Задержка появления"
L["Transition Show Hysteresis Tooltip"] = "Задержка перед отображением после того, как условие видимости стало истинным."
L["Transition Hide Hysteresis"] = "Задержка скрытия"
L["Transition Hide Hysteresis Tooltip"] = "Задержка перед скрытием после того, как условие видимости перестало быть истинным."
L["Assisted Highlight Glow Transition Enabled"] = "Включить анимацию свечения"
L["Assisted Highlight Glow Transition Enabled Tooltip"] = "Включить эффект пульсации для вспомогательной подсветки."
L["Assisted Highlight Glow Transition Speed"] = "Скорость анимации свечения"
L["Assisted Highlight Glow Transition Speed Tooltip"] = "Множитель скорости для циклов анимации свечения."
L["Assisted Highlight Glow Transition Strength"] = "Интенсивность анимации свечения"
L["Assisted Highlight Glow Transition Strength Tooltip"] = "Амплитуда пульсации: 0 - почти статично, 1 - полный диапазон пульсации."
L["Class Resource Horizontal Offset"] = "Смещение ресурса по горизонтали"
L["Class Resource Vertical Offset"] = "Смещение ресурса по вертикали"
L["Class Resource Scale"] = "Масштаб ресурса класса"
L["Class Resource Scale Tooltip"] = "Масштаб отображения ресурса текущего класса."
L["Class Resource Opacity"] = "Прозрачность ресурса класса"
L["Class Resource Opacity Tooltip"] = "Прозрачность отображения ресурса текущего класса."
L["Class Resource Visual Style"] = "Визуальный стиль"
L["Class Resource Visual Style Tooltip"] = "Классический - использует уникальные для каждого класса текстуры и анимации. Упрощенный - использует единый плоский стиль с настраиваемыми цветами заполнения."
L["Class Resource Visual Style Classic"] = "Классический"
L["Class Resource Visual Style Simple"] = "Упрощенный"
L["Class Resource Simple Animations"] = "Анимации упрощенного стиля"
L["Class Resource Simple Animations Tooltip"] = "Включить анимации накопления и траты ресурса для упрощенного стиля. Не влияет на классический режим."
L["Class Resource Fill Color Source"] = "Источник цвета заполнения"
L["Class Resource Fill Color Source Tooltip"] = "Выберите, как определяется цвет заполнения ресурса класса. Применимо к упрощенному стилю и поддерживаемым классическим системам."
L["Class Resource Fill Color Source Custom"] = "Пользовательский цвет"
L["Class Resource Fill Color Source Class"] = "Цвет класса"
L["Class Resource Fill Color Source Resource"] = "Цвет ресурса"
L["Class Resource Fill Color"] = "Цвет заполнения"
L["Class Resource Fill Color Tooltip"] = "Пользовательский цвет для активных единиц ресурса класса. Используется, когда выбран источник Пользовательский цвет."
L["Resource Color Health"] = "Здоровье"
L["Resource Color Mana"] = "Мана"
L["Resource Color Energy"] = "Энергия"
L["Resource Color Rage"] = "Ярость"
L["Resource Color Focus"] = "Концентрация"
L["Resource Color Fury"] = "Гнев"
L["Resource Color Runic Power"] = "Сила рун"
L["Resource Color Lunar Power"] = "Астральная мощь"
L["Resource Color Insanity"] = "Безумие"
L["Resource Color Maelstrom"] = "Энергия Водоворота"
L["Resource Color Runes"] = "Руны"
L["Resource Color Rogue Combo Points"] = "Приемы серии (Разбойник)"
L["Resource Color Druid Combo Points"] = "Приемы серии (Друид)"
L["Resource Color Holy Power"] = "Энергия Света"
L["Resource Color Chi"] = "Энергия Ци"
L["Resource Color Arcane Charges"] = "Чародейские заряды"
L["Resource Color Soul Shards"] = "Осколки душ"
L["Resource Color Essence"] = "Сущность"
L["Resource Color Maelstrom Weapon"] = "Оружие Водоворота"
L["Class Resource Background Color Tooltip"] = "Цвет фона для незаполненных ячеек ресурса класса."
L["Class Resource Visibility"] = "Видимость ресурса класса"
L["Class Resource Visibility Tooltip"] = "Условия отображения ресурсов класса."
L["Cast Ring Visibility"] = "Видимость кольца применения"
L["Cast Ring Visibility Tooltip"] = "Условия отображения оболочки кольца применения заклинаний."
L["Visibility Always"] = "Всегда"
L["Visibility Always Tooltip"] = "Оставлять этот элемент видимым постоянно. Выбор этого пункта сбросит остальные условия видимости."
L["Visibility In Combat"] = "В бою"
L["Visibility In Combat Tooltip"] = "Показывать, когда вы находитесь в бою."
L["Visibility Out of Combat"] = "Вне боя"
L["Visibility Out of Combat Tooltip"] = "Показывать, когда вы находитесь вне боя."
L["Visibility Has Target"] = "Есть любая цель"
L["Visibility Has Target Tooltip"] = "Показывать, когда выбрана любая цель. Вложенные параметры позволяют уточнить, какие именно цели учитывать."
L["Visibility Target Alive"] = "Живые"
L["Visibility Target Alive Tooltip"] = "Учитывать только живые цели. Сочетайте с фильтрами отношения цели для более точной настройки."
L["Visibility Target Dead"] = "Мертвые"
L["Visibility Target Dead Tooltip"] = "Учитывать только мертвые цели или призраков. Сочетайте с фильтрами отношения цели для более точной настройки."
L["Visibility Target Hostile"] = "Враждебные / Недружелюбные"
L["Visibility Target Hostile Tooltip"] = "Учитывать только враждебные цели или противников, которых можно атаковать."
L["Visibility Target Neutral"] = "Нейтральные"
L["Visibility Target Neutral Tooltip"] = "Учитывать только нейтральные цели, которые не являются дружелюбными, но и не проявляют враждебности в данный момент."
L["Visibility Target Friendly"] = "Дружелюбные"
L["Visibility Target Friendly Tooltip"] = "Учитывать только дружелюбные цели."
L["Visibility While Casting"] = "Во время заклинания"
L["Visibility While Casting Tooltip"] = "Показывать, пока вы активно произносите или поддерживаете заклинание."
L["Visibility After Instant Cast"] = "После мгновенного заклинания"
L["Visibility After Instant Cast Tooltip"] = "Кратковременно показывать после успешного применения мгновенного заклинания, которое вы активировали напрямую."
L["Visibility After Triggered Instant Cast"] = "После срабатывания заклинания"
L["Visibility After Triggered Instant Cast Tooltip"] = "Кратковременно показывать после успешного применения мгновенного заклинания, вызванного автоматически другим действием или эффектом (проком)."
L["Visibility In Party"] = "В группе"
L["Visibility In Party Tooltip"] = "Показывать, когда вы находитесь в группе (но не в рейде)."
L["Visibility In Raid"] = "В рейде"
L["Visibility In Raid Tooltip"] = "Показывать, когда вы находитесь в составе рейдовой группы."
L["Visibility In Instanced Content"] = "В подземельях и сценариях"
L["Visibility In Instanced Content Tooltip"] = "Показывать, когда вы находитесь внутри инстанса (подземелье, рейд, сценарий или арена)."
L["Hide While In Pet Battle"] = "Скрывать в битвах питомцев"
L["Hide While In Pet Battle Tooltip"] = "Скрывать SparkPoint, пока вы участвуете в битве питомцев."
L["Hide While In Special Action Bar Context"] = "Скрывать при особых панелях действий"
L["Hide While In Special Action Bar Context Tooltip"] =
	"Скрывать SparkPoint, когда стандартная панель заменяется особой (транспорт, контроль над персонажем, превращение или замена панелей)."
L["Visibility Multi Select Tooltip"] = "Выберите одно или несколько правил. Элемент будет отображаться, если хотя бы одно из условий верно."
L["Decorative Ring Size"] = "Размер"
L["Decorative Ring Rotate"] = "Вращение"
L["Decorative Ring Texture"] = "Текстура"
L["Decorative Ring Color"] = "Цвет"
L["Decorative Ring Visibility"] = "Видимость"
L["Decorative Ring Visibility Tooltip"] = "Условия отображения декоративного кольца."
L["Decorative Ring Use Class Color"] = "Цвет класса"
L["Decorative Ring Use Class Color Tooltip"] = "Переопределить цвет кольца цветом вашего класса."
L["Decorative Ring Class Color Opacity"] = "Прозрачность цвета класса"
L["Decorative Ring Class Color Opacity Tooltip"] = "Прозрачность при использовании цвета класса."
L["Spell Icon Size"] = "Размер"
L["Spell Icon Horizontal Offset"] = "Смещение иконки по горизонтали"
L["Spell Icon Vertical Offset"] = "Смещение иконки по вертикали"
L["Cast Progress Swipe"] = "Затенение прогресса"
L["Cast Progress Swipe Color"] = "Цвет затенения"
L["Cast Progress Swipe Color Tooltip"] = "Цвет и прозрачность эффекта затенения прогресса на иконке заклинания."
L["Readable Cooldown Use Class Color"] = "Цвет класса"
L["Readable Cooldown Use Class Color Tooltip"] = "Переопределить цвет затенения восстановления цветом вашего класса, сохраняя заданную прозрачность."
L["Readable Cooldown Swipe Color"] = "Цвет затенения восстановления"
L["Readable Cooldown Swipe Color Tooltip"] = "Цвет и прозрачность эффекта затенения восстановления, который отображается после неудачного нажатия."
L["Show On Instant Casts"] = "Для мгновенных заклинаний"
L["Show On Instant Casts Tooltip"] = "Кратковременно отображать иконку способности при использовании мгновенных заклинаний."
L["Assisted Highlight Size"] = "Размер подсветки"
L["Assisted Highlight Horizontal Offset"] = "Смещение по горизонтали"
L["Assisted Highlight Vertical Offset"] = "Смещение по вертикали"
L["Assisted Highlight Icon Opacity"] = "Прозрачность иконки"
L["Assisted Highlight Icon Opacity Tooltip"] = "Прозрачность иконки заклинания во вспомогательной подсветке."
L["Assisted Highlight Glow"] = "Свечение"
L["Assisted Highlight Glow Tooltip"] = "Отображать синее свечение вокруг иконки рекомендованного заклинания."
L["Assisted Highlight Glow Color"] = "Цвет свечения"
L["Assisted Highlight Glow Color Tooltip"] = "Цвет и прозрачность слоя свечения для вспомогательной подсветки."
L["Assisted Highlight Keybind Text"] = "Текст горячих клавиш"
L["Assisted Highlight Keybind Text Tooltip"] = "Показывать назначенную клавишу для рекомендованного заклинания (если доступно)."
L["Assisted Highlight Keybind Format"] = "Формат клавиш"
L["Assisted Highlight Keybind Format Tooltip"] = "Выберите стиль отображения клавиш: краткий или полный."
L["Assisted Highlight Keybind Compact"] = "Краткий"
L["Assisted Highlight Keybind Full"] = "Полный"
L["Assisted Highlight Keybind Font"] = "Шрифт клавиш"
L["Assisted Highlight Keybind Font Outline"] = "Контур шрифта клавиш"
L["Assisted Highlight Keybind Font Size"] = "Размер шрифта клавиш"
L["Assisted Highlight Keybind Opacity"] = "Прозрачность клавиш"
L["Assisted Highlight Keybind Opacity Tooltip"] = "Множитель прозрачности для текста горячих клавиш."
L["Assisted Highlight Keybind Horizontal Offset"] = "Смещение клавиш по горизонтали"
L["Assisted Highlight Keybind Vertical Offset"] = "Смещение клавиш по вертикали"
L["Assisted Highlight Keybind Color"] = "Цвет текста клавиш"
L["Assisted Highlight Keybind Color Tooltip"] = "Цвет и прозрачность текста горячих клавиш во вспомогательной подсветке."
L["Assisted Highlight CVar Disabled"] = "Вспомогательная подсветка Blizzard сейчас отключена. Включите её в настройках игры, чтобы видеть рекомендации."
L["Assisted Highlight Visibility"] = "Видимость подсветки"
L["Assisted Highlight Visibility Tooltip"] = "Условия отображения иконки вспомогательной подсветки."

--------------------------------------------------------------------------------
-- Cast Ring
--------------------------------------------------------------------------------
L["Cast Ring"] = "Кольцо заклинаний"
L["Cast Ring Description"] = "Отображает кольцо прогресса вокруг курсора во время применения заклинаний."
L["Reverse Channeling"] = "Инверсия потоковых заклинаний"
L["Reverse Channeling Tooltip"] = "Изменить направление заполнения для потоковых заклинаний."
L["Cast Progress Display"] = "Отображение прогресса"
L["Cast Progress Display Tooltip"] = "Выберите, для каких типов заклинаний анимировать заполнение кольца. Это не влияет на общую видимость SparkPoint."
L["Cast Progress Display All"] = "Все заклинания"
L["Cast Progress Display Normal"] = "Только обычные"
L["Cast Progress Display Channelled"] = "Только потоковые"
L["Cast Fill Color Source"] = "Источник цвета заполнения"
L["Cast Fill Color Source Tooltip"] = "Выберите, как определяется основной цвет заполнения кольца."
L["Cast Fill Color Source Single"] = "Один цвет"
L["Cast Fill Color Source Split"] = "Разные цвета (Обычные / Потоковые)"
L["Cast Fill Color Source Class"] = "Цвет класса"
L["Primary Cast Color"] = "Основной цвет заклинаний"
L["Primary Cast Color Tooltip"] = "Используется для всех заклинаний в режиме одного цвета или для обычных (не потоковых) в раздельном режиме."
L["Channelled Cast Color"] = "Цвет потоковых заклинаний"
L["Channelled Cast Color Tooltip"] = "Цвет заполнения кольца во время поддержания потокового заклинания."
L["Show Spell Name"] = "Показывать название"
L["Show Spell Name Tooltip"] = "Отображать название заклинания над кольцом."
L["Spell Text Size"] = "Размер текста заклинания"

--------------------------------------------------------------------------------
-- Class Resource
--------------------------------------------------------------------------------
L["Class Resource"] = "Ресурс класса"
L["Class Resource Description"] = "Отображает ресурсы класса (приемы серии, руны, сущности и др.) рядом с курсором."
L["Class Power"] = "Энергия класса"
L["Bar Slots Description"] = "Отображает изогнутые полосы-слоты над и под кольцом заклинаний."

--------------------------------------------------------------------------------
-- Ring
--------------------------------------------------------------------------------
L["Decorative Ring"] = "Декоративное кольцо"
L["Decorative Ring Description"] = "Отображает декоративное вращающееся кольцо вокруг курсора во время применения заклинаний."

--------------------------------------------------------------------------------
-- Spell Icon
--------------------------------------------------------------------------------
L["Spell Icon"] = "Иконка заклинания"
L["Spell Icon Description"] = "Отображает иконку применяемого заклинания рядом с курсором."
L["Show On Instant Casts"] = "Для мгновенных заклинаний"
L["Show On Instant Casts Tooltip"] = "Кратковременно отображать иконку для мгновенных способностей, которые вы активируете напрямую."
L["Show Triggered Instant Casts"] = "Для сработавших способностей"
L["Show Triggered Instant Casts Tooltip"] = "Также отображать мгновенные заклинания, сработавшие автоматически после вашего действия (например, проки или последующие эффекты)."
L["Failed Cast Style"] = "Стиль при неудачном касте"
L["Failed Cast Style Tooltip"] = "Выберите, как иконка реагирует на неудачную попытку применить заклинание по причинам, не связанным с восстановлением (КД)."
L["Failed Cast Style Hide"] = "Скрывать"
L["Failed Cast Style Error Icon"] = "Иконка ошибки"
L["Show Cooldown Blocked Presses"] = "Показывать КД при нажатии"
L["Show Cooldown Blocked Presses Tooltip"] = "Отображать иконку с оставшимся временем восстановления только тогда, когда игра предоставляет данные о КД для нажатой способности."

--------------------------------------------------------------------------------
-- Assisted Highlight
--------------------------------------------------------------------------------
L["Assisted Highlight"] = "Вспомогательная подсветка"
L["Assisted Highlight Description"] = "Отображает следующее рекомендованное заклинание на основе системы подсказок Blizzard."

--------------------------------------------------------------------------------
-- Performance Stats
--------------------------------------------------------------------------------
L["Performance Stats"] = "Статистика производительности"
L["Performance Stats Description"] = "Отображает потребление памяти и процессора аддоном SparkPoint рядом с курсором."
L["Performance Stats Font"] = "Шрифт статистики"
L["Performance Stats Font Tooltip"] = "Выберите шрифт для текста статистики производительности."
L["Performance Stats Font Outline"] = "Контур шрифта"
L["Performance Stats Font Outline Tooltip"] = "Выберите стиль контура для текста статистики."
L["Performance Stats Font Size"] = "Размер шрифта"
L["Performance Stats Font Size Tooltip"] = "Размер шрифта для текста статистики производительности."
L["Performance Stats Color"] = "Цвет текста"
L["Performance Stats Color Tooltip"] = "Цвет и прозрачность текста статистики производительности."
L["Performance Stats Horizontal Offset"] = "Смещение по горизонтали"
L["Performance Stats Vertical Offset"] = "Смещение по вертикали"
L["Performance Stats Visibility Tooltip"] = "Условия отображения текста статистики производительности."

--------------------------------------------------------------------------------
-- Colors (for future use)
--------------------------------------------------------------------------------
L["Bar Color"] = "Цвет полосы"
L["Background Color"] = "Цвет фона"
L["Spark Color"] = "Цвет искры"
L["Latency Color"] = "Цвет задержки"
L["Font Color"] = "Цвет шрифта"

--------------------------------------------------------------------------------
-- Messages
--------------------------------------------------------------------------------
L["Position locked"] = "Позиция закреплена."
L["Drag to reposition"] = "Перетащите, чтобы изменить позицию. ПКМ - закрепить."
L["Position reset"] = "Сброс позиции к настройкам по умолчанию."
